name: Deploy to DigitalOcean

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_ADDRESS }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ${{ secrets.DO_PROJECT_FOLDER }}
            git fetch
            git checkout main
            git pull
            rm .env
            touch .env
            echo API_URL=${{ secrets.API_URL }} >> .env
            echo API_KEY=${{ secrets.API_KEY }} >> .env
            echo NEXT_PUBLIC_ASSET_URL=${{ secrets.NEXT_PUBLIC_ASSET_URL }} >> .env
            cat .env
            yarn install
            yarn build
            yarn storybook:build
            pm2 list
            pm2 delete sportdb-react
            pm2 start yarn --name sportdb-react -- start
